#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import random
import re
from collections import Counter
from pathlib import Path
from statistics import median


def score_doc(doc: dict) -> dict:
    ext = doc.get("extract", {})
    merged = ext.get("merged", {})
    text = merged.get("text", "") or ""
    chars = int(merged.get("chars") or 0)
    cpp = merged.get("chars_per_page")
    cpp_extracted = merged.get("chars_per_extracted_page")
    coverage_ratio = merged.get("extraction_coverage_ratio")
    selected_source = merged.get("selected_source")
    pages = (((ext.get("pdfinfo") or {}).get("pages")) if "pdfinfo" in ext else None)

    lines = [x.strip() for x in text.splitlines() if x.strip()]
    uniq_line_ratio = (len(set(lines)) / len(lines)) if lines else 0.0
    boiler_hits = 0
    patt = [
        r"document generated by anna['’]s archive",
        r"copyright",
        r"all rights reserved",
        r"目\s*录",
        r"contents",
    ]
    low = text.lower()
    for p in patt:
        if re.search(p, low):
            boiler_hits += 1

    flags = []
    if chars < 200:
        flags.append("too_short")
    rate_for_quality = cpp_extracted if isinstance(cpp_extracted, (int, float)) else cpp
    if isinstance(rate_for_quality, (int, float)) and rate_for_quality < 40:
        flags.append("low_chars_per_page")
    if isinstance(coverage_ratio, (int, float)) and coverage_ratio < 0.2:
        flags.append("partial_coverage")
    if "document generated by anna" in low:
        flags.append("anna_archive_marker")
    if uniq_line_ratio < 0.25 and len(lines) > 80:
        flags.append("high_line_duplication")
    if boiler_hits >= 2 and chars < 3000:
        flags.append("boilerplate_dominant")

    # Grade heuristic
    if "anna_archive_marker" in flags or chars < 120:
        grade = "F"
    elif "low_chars_per_page" in flags or chars < 1000:
        grade = "D"
    elif chars < 4000:
        grade = "C"
    elif (isinstance(cpp, (int, float)) and cpp >= 120) or chars >= 12000:
        grade = "A" if uniq_line_ratio >= 0.5 else "B"
    else:
        grade = "B"

    return {
        "doc_id": doc.get("doc_id"),
        "relative_path": doc.get("relative_path"),
        "source_group": doc.get("source_group"),
        "status": doc.get("status"),
        "file_type": doc.get("file_type"),
        "chars": chars,
        "pages": pages,
        "chars_per_page": cpp,
        "chars_per_extracted_page": cpp_extracted,
        "coverage_ratio": coverage_ratio,
        "selected_source": selected_source,
        "uniq_line_ratio": round(uniq_line_ratio, 3),
        "flags": flags,
        "grade": grade,
    }


def choose_samples(rows: list[dict], n: int, seed: int) -> list[dict]:
    random.seed(seed)
    by_grade = {}
    for r in rows:
        by_grade.setdefault(r["grade"], []).append(r)

    out: list[dict] = []
    # Ensure low-quality docs are always sampled
    for g in ["F", "D", "C", "B", "A"]:
        pool = by_grade.get(g, [])
        if not pool:
            continue
        take = min(max(1, n // 10), len(pool)) if g in {"F", "D"} else min(max(1, n // 20), len(pool))
        out.extend(random.sample(pool, take))

    if len(out) < n:
        rest = [r for r in rows if r not in out]
        out.extend(random.sample(rest, min(n - len(out), len(rest))))

    return sorted(out[:n], key=lambda x: (x["grade"], x["chars"]))


def main() -> int:
    ap = argparse.ArgumentParser(description="Assess raw extraction quality.")
    ap.add_argument("--input", default="data/processed/extract_raw")
    ap.add_argument("--sample-size", type=int, default=24)
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    root = Path(args.input).resolve()
    docs_dir = root / "docs"
    report_dir = root / "reports"
    report_dir.mkdir(parents=True, exist_ok=True)

    docs = sorted(docs_dir.glob("*.json"))
    if not docs:
        print("No extracted docs found")
        return 1

    rows = []
    for p in docs:
        obj = json.loads(p.read_text(encoding="utf-8"))
        rows.append(score_doc(obj))

    grades = Counter(r["grade"] for r in rows)
    flags = Counter(f for r in rows for f in r["flags"])
    chars = [r["chars"] for r in rows]
    cpp = [r["chars_per_page"] for r in rows if isinstance(r["chars_per_page"], (int, float))]
    cpp_ex = [r["chars_per_extracted_page"] for r in rows if isinstance(r["chars_per_extracted_page"], (int, float))]

    summary = {
        "total_docs": len(rows),
        "grade_distribution": dict(grades),
        "flag_distribution": dict(flags),
        "chars": {
            "min": min(chars),
            "median": int(median(chars)),
            "max": max(chars),
        },
        "chars_per_page": {
            "min": round(min(cpp), 2) if cpp else None,
            "median": round(median(cpp), 2) if cpp else None,
            "max": round(max(cpp), 2) if cpp else None,
        },
        "chars_per_extracted_page": {
            "min": round(min(cpp_ex), 2) if cpp_ex else None,
            "median": round(median(cpp_ex), 2) if cpp_ex else None,
            "max": round(max(cpp_ex), 2) if cpp_ex else None,
        },
        "pass_rate_B_or_above": round(sum(1 for r in rows if r["grade"] in {"A", "B"}) / len(rows), 4),
        "pass_rate_C_or_above": round(sum(1 for r in rows if r["grade"] in {"A", "B", "C"}) / len(rows), 4),
    }

    samples = choose_samples(rows, args.sample_size, args.seed)
    low = sorted(rows, key=lambda x: (x["grade"], x["chars"]))[:30]

    (report_dir / "quality_summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    (report_dir / "quality_scored.jsonl").write_text("\n".join(json.dumps(r, ensure_ascii=False) for r in rows) + "\n", encoding="utf-8")
    (report_dir / "quality_samples.json").write_text(json.dumps(samples, ensure_ascii=False, indent=2), encoding="utf-8")
    (report_dir / "quality_lowest30.json").write_text(json.dumps(low, ensure_ascii=False, indent=2), encoding="utf-8")

    print(json.dumps(summary, ensure_ascii=False, indent=2))
    print(f"samples: {report_dir / 'quality_samples.json'}")
    print(f"lowest:  {report_dir / 'quality_lowest30.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
