#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import random
import re
from collections import Counter
from pathlib import Path
from statistics import median


QUALITY_GATE = {
    "min_pass_rate_B_or_above": 0.90,
    "max_p95_cjk_space_ratio": 0.08,
    "max_ratio_docs_cjk_space_gt_0_20": 0.05,
    "max_p95_noisy_line_ratio": 0.12,
    "max_f_grade_ratio": 0.03,
}


def score_doc(obj: dict) -> dict:
    clean = obj.get("clean", {})
    text = clean.get("text", "") or ""
    stats = clean.get("stats", {})
    flags = set(clean.get("flags", []))

    chars = len(text)
    pages = int(stats.get("pages") or 0)
    cpp = chars / max(pages, 1)
    lines = [x.strip() for x in text.splitlines() if x.strip()]
    uniq_ratio = len(set(lines)) / max(len(lines), 1)

    weird = len(re.findall(r"[�□■◆▲▼※¤§]", text)) / max(chars, 1)
    page_markers = len(re.findall(r"\[PAGE\s+\d+\]", text))
    cjk_chars = len(re.findall(r"[\u4e00-\u9fff]", text))
    cjk_spaces = len(re.findall(r"(?<=[\u4e00-\u9fff])\s+(?=[\u4e00-\u9fff])", text))
    cjk_space_ratio = cjk_spaces / max(cjk_chars, 1)
    punct_space = len(re.findall(r"\s+[，。！？；：、]", text))
    punct_space_ratio = punct_space / max(cjk_chars, 1)
    ascii_punct_gap = len(re.findall(r"(?<=[\u4e00-\u9fff])\s+[,.;:!?]|[,.;:!?]\s+(?=[\u4e00-\u9fff])", text))
    ascii_punct_gap_ratio = ascii_punct_gap / max(cjk_chars, 1)
    noisy_lines = 0
    for ln in lines:
        toks = ln.split()
        if len(ln) < 24 or len(toks) < 6:
            continue
        short_ratio = sum(1 for t in toks if len(t) <= 2) / len(toks)
        odd_symbols = len(re.findall(r"[`~^_|\\¤§¥£©®™′]", ln))
        cjk_ln = len(re.findall(r"[\u4e00-\u9fff]", ln))
        if odd_symbols >= 3 or (short_ratio > 0.65 and odd_symbols >= 1 and cjk_ln < 160):
            noisy_lines += 1
    noisy_line_ratio = noisy_lines / max(len(lines), 1)

    risk: list[str] = []
    low = text.lower()
    if "document generated by anna" in low:
        risk.append("metadata_left")
    if chars < 500:
        risk.append("too_short")
    if cpp < 80:
        risk.append("low_cpp")
    if weird > 0.01:
        risk.append("weird_chars_high")
    if uniq_ratio < 0.22 and len(lines) > 120:
        risk.append("dup_lines_high")
    if page_markers == 0:
        risk.append("no_page_marker")
    if cjk_chars > 300 and cjk_space_ratio > 0.12:
        risk.append("cjk_spacing_severe")
    elif cjk_chars > 300 and cjk_space_ratio > 0.04:
        risk.append("cjk_spacing_mild")
    if cjk_chars > 300 and punct_space_ratio > 0.01:
        risk.append("punct_spacing_high")
    if cjk_chars > 300 and ascii_punct_gap_ratio > 0.01:
        risk.append("ascii_punct_spacing_high")
    if noisy_line_ratio > 0.20:
        risk.append("noisy_lines_severe")
    elif noisy_line_ratio > 0.10:
        risk.append("noisy_lines_mild")

    risk.extend(sorted(flags))
    risk = sorted(set(risk))

    if "metadata_left" in risk or "too_short" in risk:
        grade = "F"
    elif "weird_chars_high" in risk or "low_cpp" in risk or "cjk_spacing_severe" in risk or "noisy_lines_severe" in risk:
        grade = "D"
    elif "dup_lines_high" in risk or "cjk_spacing_mild" in risk or "punct_spacing_high" in risk or "ascii_punct_spacing_high" in risk or "noisy_lines_mild" in risk:
        grade = "C"
    else:
        grade = "A" if cpp >= 300 and uniq_ratio >= 0.45 else "B"

    return {
        "doc_id": obj.get("doc_id"),
        "relative_path": obj.get("relative_path"),
        "source_group": obj.get("source_group"),
        "grade": grade,
        "chars": chars,
        "pages": pages,
        "chars_per_page": round(cpp, 2),
        "uniq_line_ratio": round(uniq_ratio, 3),
        "cjk_chars": cjk_chars,
        "cjk_space_ratio": round(cjk_space_ratio, 4),
        "punct_space_ratio": round(punct_space_ratio, 4),
        "ascii_punct_gap_ratio": round(ascii_punct_gap_ratio, 4),
        "noisy_line_ratio": round(noisy_line_ratio, 4),
        "risk_flags": risk,
    }


def choose_samples(rows: list[dict], n: int, seed: int) -> list[dict]:
    random.seed(seed)
    by_grade: dict[str, list[dict]] = {}
    for r in rows:
        by_grade.setdefault(r["grade"], []).append(r)

    out: list[dict] = []
    for g in ["F", "D", "C", "B", "A"]:
        pool = by_grade.get(g, [])
        if not pool:
            continue
        k = min(max(1, n // 10), len(pool)) if g in {"F", "D"} else min(max(1, n // 20), len(pool))
        out.extend(random.sample(pool, k))

    if len(out) < n:
        rest = [r for r in rows if r not in out]
        out.extend(random.sample(rest, min(n - len(out), len(rest))))

    return sorted(out[:n], key=lambda x: (x["grade"], x["chars"]))


def main() -> int:
    ap = argparse.ArgumentParser(description="Assess cleaned corpus quality")
    ap.add_argument("--input", default="data/processed/cleaned_full")
    ap.add_argument("--sample-size", type=int, default=24)
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    root = Path(args.input).resolve()
    docs = sorted((root / "docs").glob("*.json"))
    reports = root / "reports"
    reports.mkdir(parents=True, exist_ok=True)

    if not docs:
        print("No cleaned docs found")
        return 1

    scored = [score_doc(json.loads(p.read_text(encoding="utf-8"))) for p in docs]
    grade_dist = Counter(r["grade"] for r in scored)
    flag_dist = Counter(f for r in scored for f in r["risk_flags"])
    chars = [r["chars"] for r in scored]
    cpp = [r["chars_per_page"] for r in scored]
    cjk_space = sorted(r["cjk_space_ratio"] for r in scored)
    punct_space = sorted(r["punct_space_ratio"] for r in scored)
    ascii_punct_gap = sorted(r["ascii_punct_gap_ratio"] for r in scored)
    noisy_line_ratio = sorted(r["noisy_line_ratio"] for r in scored)
    ratio_gt_020 = sum(1 for x in cjk_space if x > 0.20) / len(cjk_space)
    p95_idx = min(len(cjk_space) - 1, int(len(cjk_space) * 0.95))
    cjk_space_p95 = cjk_space[p95_idx]
    noisy_line_p95 = noisy_line_ratio[min(len(noisy_line_ratio) - 1, int(len(noisy_line_ratio) * 0.95))]
    f_ratio = grade_dist.get("F", 0) / len(scored)

    summary = {
        "total_docs": len(scored),
        "grade_distribution": dict(grade_dist),
        "flag_distribution": dict(flag_dist),
        "chars": {"min": min(chars), "median": int(median(chars)), "max": max(chars)},
        "chars_per_page": {"min": min(cpp), "median": round(median(cpp), 2), "max": max(cpp)},
        "cjk_space_ratio": {"min": min(cjk_space), "median": round(median(cjk_space), 4), "p95": round(cjk_space_p95, 4), "max": max(cjk_space)},
        "punct_space_ratio": {"min": min(punct_space), "median": round(median(punct_space), 4), "p95": round(punct_space[min(len(punct_space) - 1, int(len(punct_space) * 0.95))], 4), "max": max(punct_space)},
        "ascii_punct_gap_ratio": {"min": min(ascii_punct_gap), "median": round(median(ascii_punct_gap), 4), "p95": round(ascii_punct_gap[min(len(ascii_punct_gap) - 1, int(len(ascii_punct_gap) * 0.95))], 4), "max": max(ascii_punct_gap)},
        "noisy_line_ratio": {"min": min(noisy_line_ratio), "median": round(median(noisy_line_ratio), 4), "p95": round(noisy_line_ratio[min(len(noisy_line_ratio) - 1, int(len(noisy_line_ratio) * 0.95))], 4), "max": max(noisy_line_ratio)},
        "ratio_docs_cjk_space_gt_0_20": round(ratio_gt_020, 4),
        "pass_rate_B_or_above": round(sum(1 for r in scored if r["grade"] in {"A", "B"}) / len(scored), 4),
        "pass_rate_C_or_above": round(sum(1 for r in scored if r["grade"] in {"A", "B", "C"}) / len(scored), 4),
        "quality_gate": {
            "thresholds": QUALITY_GATE,
            "actual": {
                "pass_rate_B_or_above": round(sum(1 for r in scored if r["grade"] in {"A", "B"}) / len(scored), 4),
                "p95_cjk_space_ratio": round(cjk_space_p95, 4),
                "ratio_docs_cjk_space_gt_0_20": round(ratio_gt_020, 4),
                "p95_noisy_line_ratio": round(noisy_line_p95, 4),
                "f_grade_ratio": round(f_ratio, 4),
            },
            "passed": (
                (sum(1 for r in scored if r["grade"] in {"A", "B"}) / len(scored)) >= QUALITY_GATE["min_pass_rate_B_or_above"]
                and cjk_space_p95 <= QUALITY_GATE["max_p95_cjk_space_ratio"]
                and ratio_gt_020 <= QUALITY_GATE["max_ratio_docs_cjk_space_gt_0_20"]
                and noisy_line_p95 <= QUALITY_GATE["max_p95_noisy_line_ratio"]
                and f_ratio <= QUALITY_GATE["max_f_grade_ratio"]
            ),
        },
    }

    samples = choose_samples(scored, args.sample_size, args.seed)
    low = sorted(scored, key=lambda x: (x["grade"], x["chars"]))[:30]
    keep_ab = [r for r in scored if r["grade"] in {"A", "B"}]
    review_cd = [r for r in scored if r["grade"] in {"C", "D", "F"}]

    summary["for_kgrag"] = {
        "keep_A_B": len(keep_ab),
        "review_C_or_lower": len(review_cd),
    }

    (reports / "clean_quality_summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    (reports / "clean_quality_scored.jsonl").write_text("\n".join(json.dumps(r, ensure_ascii=False) for r in scored) + "\n", encoding="utf-8")
    (reports / "clean_quality_samples.json").write_text(json.dumps(samples, ensure_ascii=False, indent=2), encoding="utf-8")
    (reports / "clean_quality_lowest30.json").write_text(json.dumps(low, ensure_ascii=False, indent=2), encoding="utf-8")
    (reports / "clean_quality_keep_A_B.jsonl").write_text("\n".join(json.dumps(r, ensure_ascii=False) for r in keep_ab) + "\n", encoding="utf-8")
    (reports / "clean_quality_review_C_or_lower.jsonl").write_text("\n".join(json.dumps(r, ensure_ascii=False) for r in review_cd) + "\n", encoding="utf-8")

    print(json.dumps(summary, ensure_ascii=False, indent=2))
    print(f"samples: {reports / 'clean_quality_samples.json'}")
    print(f"lowest:  {reports / 'clean_quality_lowest30.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
